name: Setup Frontend
description: Common setup for frontend jobs using bun
runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        cache: true
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version-file: frontend/.nvmrc
        cache-dependency-path: frontend/bun.lock
    - name: Install dependencies
      working-directory: frontend
      run: bun install --frozen-lockfile
      shell: bash
