name: Setup Frontend
description: Common setup for frontend jobs using pnpm
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      with:
        run_install: false
        package_json_file: frontend/package.json
    - name: Get pnpm store directory
      id: pnpm-store
      run: echo "dir=$(pnpm store path)" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: pnpm store cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: ${{ steps.pnpm-store.outputs.dir }}
        key: pnpm-store-${{ runner.os }}-${{ hashFiles('frontend/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-store-${{ runner.os }}-
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version-file: frontend/.nvmrc
        cache: 'pnpm'
        cache-dependency-path: frontend/pnpm-lock.yaml
    - name: Install dependencies
      working-directory: frontend
      run: pnpm install --frozen-lockfile --prefer-offline
      shell: bash
