version: '3'

services:
  api:
    image: vikunja/api:unstable@sha256:61b77af0f0ed5b0e4c3ee693a79926d8633712ddb245f8212ba5e5321485d330
    environment:
      VIKUNJA_LOG_LEVEL: DEBUG
      # Replace with your own testing token via environment variable
      VIKUNJA_SERVICE_TESTINGTOKEN: ${VIKUNJA_SERVICE_TESTINGTOKEN:-<testing-token>}
    ports:
      - 3456:3456
  cypress:
    image: cypress/browsers:node18.12.0-chrome107@sha256:bfdbf9b64fdaad364f6e76e3c2a75fbce7c8018644d71e41ef43bba0ae8f4e38
    volumes:
    - ..:/project
    - $HOME/.cache:/home/node/.cache/
    user: node
    working_dir: /project
    environment:
      CYPRESS_API_URL: http://api:3456/api/v1
      # Provide the secret via CYPRESS_TEST_SECRET env var when running tests
      CYPRESS_TEST_SECRET: ${CYPRESS_TEST_SECRET:-<testing-secret>}
