// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Query = 1,
  Expr = 2,
  Term = 3,
  Field = 4,
  Operator = 5,
  Value = 6,
  DString = 7,
  SString = 8,
  Number = 9,
  Word = 10,
  LParen = 11,
  RParen = 12,
  Join = 13
