name: ci

env:
  DO_NOT_TRACK: 1

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    name: Release
    if: ${{ github.ref_type == 'tag' || github.ref_name == 'main' }}
    uses: ./.github/workflows/release.yml
    needs:
      - test
    secrets: inherit

  visualizer:
    name: Publish Visualizer Stats
    if: ${{ github.ref_name == 'main' || github.event_name == 'pull_request' }}
    uses: ./.github/workflows/visualizer.yml
    needs:
      - test
    secrets: inherit
